
const rizzList = [
    "I was going to wait a day to text you, but I couldn’t wait to talk to the most beautiful girl I’ve ever met.",
    "I’m not a photographer, but I can definitely picture us together.",
    "Are you a star? Because your beauty lights up my world.",
    "I’m not saying you’re perfect… but you’re pretty close.",
    "If you were a fruit, you’d be a fineapple.",
    "Are you Netflix? Because I could watch you for hours.",
    "Are you a bank loan? Because you’ve got my interest.",

    "You’re the only notification I never want to mute",
    "You’re the rhythm that makes my heart freestyle",
    "You’re the sparkle my dull days missed",
    "You’re the muse that turns my silence into art",

 
    "You’re the glow that outshines my screens",
    "You’re the calm wave in my raging ocean",
    "You’re the melody that gives life to my lyrics",
    "You’re the spark that ignites my frozen heart",
    "You’re the dream that reality can’t compete with",
    "You’re the lighthouse in my foggy mornings",
    "You’re the rhythm that dances in my veins",
    "You’re the shimmer in my grayscale world",
    "You’re the muse that makes my words flow effortlessly",
    "You’re the gentle breeze after my storms",
    "You’re the pulse behind my every thought",
    "You’re the glow that fills my dark corners",
    "You’re the whisper that calms my wildest fears",
    "You’re the melody that plays even in my silence",
    "You’re the anchor that keeps me grounded",
    "You’re the spark that starts my every morning",
    "You’re the muse that colors my imagination",
    "You’re the rhythm in my unpredictable days",
    "You’re the light at the end of my tunnel",
    "You’re the spark that electrifies my ideas",
    "You’re the glow that makes sunsets jealous",
    "You’re the song that never gets old",
    "You’re the calm after my emotional storms",
    "You’re the muse of my spontaneous poems",
    "You’re the spark that lights my unspoken feelings",
    "You’re the rhythm that sets my mood",
    "You’re the melody that hums through my soul",
    "You’re the anchor in my chaotic thoughts",
    "You’re the glow that brightens my mundane",
    "You’re the whisper that softens my worries",
    "You’re the breeze that cools my heated mind",
    "You’re the pulse that keeps my heart alive",
    "You’re the lighthouse that guides me through my doubts",
    "You’re the spark that burns in my cold nights",
    "You’re the muse that crafts my finest lyrics",
    "You’re the rhythm that brings balance to my steps",
    "You’re the glow that lights up my grey days",
    "You’re the melody that makes my silence musical",
    "You’re the calm wave washing over my anxiety",
    "You’re the shimmer that outshines the stars",
    "You’re the anchor that stops me from drifting",
    "You’re the spark that revives my energy",
    "You’re the muse behind my midnight writings",
    "You’re the rhythm that keeps me moving forward",
    "You’re the glow that bathes my soul in light",
    "You’re the melody I never want to end",
    "You’re the calm in my inner chaos",
    "You’re the breeze that whispers hope",
    "You’re the pulse that gives me life",
    "You’re the lighthouse of my destiny",
    "You’re the spark that fires up my purpose",
    "You’re the muse that brings my words alive",
    "You’re the rhythm that makes my heart skip",
    "You’re the glow that paints my world vibrant",
    "You’re the melody that echoes in my dreams",
    "You’re the calmness I find in your smile",
    "You’re the breeze that carries my worries away",
    "You’re the pulse that beats in my every thought",
    "You’re the anchor of my emotional tides",
    "You’re the spark that fuels my ambitions",
    "You’re the muse that perfects my imperfections",
    "You’re the rhythm that shapes my journey",
    "You’re the glow that lights up my every glance at you",
    "You’re the melody I keep humming unconsciously",
    "You’re the calm after my sleepless nights",
    "You’re the breeze in my suffocating moments",
    "You’re the pulse that aligns my heartbeat",
    "You’re the lighthouse showing me clarity",
    "You’re the spark in my daily monotony",
    "You’re the muse of my spontaneous stories",
    "You’re the rhythm to my life’s verses",
    "You’re the glow that makes my world softer",
    "You’re the melody that never fades in my memory",
    "You’re the calm ocean I dive into",
    "You’re the breeze that flutters my pages",
    "You’re the pulse that resonates in my chest",
    "You’re the anchor amidst my drifting thoughts",
    "You’re the spark that revives my lost hopes",
    "You’re the muse scripting my beautiful moments",
    "You’re the rhythm that orchestrates my heartbeat",
    "You’re the glow that turns my shadows into art",
    "You’re the melody that sweetens my silence",
    "You’re the calm sky above my storms",
    "You’re the breeze that turns my chaos into calm",
    "You’re the pulse driving my passion",
    "You’re the lighthouse of my dreams",
    "You’re the spark that ignites my creativity",
    "You’re the muse that fuels my fire",
    "You’re the rhythm behind my confidence",
    "You’re the glow that completes my canvas",
    "You’re the melody that flows through my veins",
    "You’re the calm that silences my noise",
    "You’re the breeze brushing away my doubts",
    "You’re the pulse that revives my spirit",
    "You’re the anchor of my emotions",
    "You’re the spark that electrifies my goals",
    "You’re the muse who translates my feelings into words",
    "You’re the rhythm keeping me grounded",
    "You’re the glow that fills my mornings with hope",
    "You’re the melody that keeps me sane",
    "You’re the calm I find in your embrace",
    "You’re the breeze that cools my restless soul",
    "You’re the pulse of my truest desires",
    "You’re the lighthouse in my foggy paths",
    "You’re the spark that sets my plans in motion",
    "You’re the muse that whispers stories into my mind",
    "You’re the rhythm that makes my thoughts dance",
    "You’re the glow that radiates from within you",
    "You’re the melody that defines my days",
    "You’re the calm that I crave after the storm",
    "You’re the breeze that sails my dreams",
    "You’re the pulse that gives my thoughts rhythm",
    "You’re the anchor of my peaceful mind",
    "You’re the spark that starts my new beginnings",
    "You’re the muse that paints my blank pages",
    "You’re the rhythm syncing with my soul",
    "You’re the glow that makes my dreams visible",
    "You’re the melody in my daily hum",
    "You’re the calm lullaby to my restless heart",
    "You’re the breeze in my poetic evenings",
    "You’re the pulse of my creative flow",
    "You’re the lighthouse in my dark moments",
    "You’re the spark that lights my every step",
    "You’re the muse behind my inner peace",
    "You’re the rhythm that plays when I’m with you",
    "You’re the glow that colors my silent nights",
    "You’re the melody that gives words to my emotions",
    "You’re the calm I find when I see you",
    "You’re the breeze that fans my excitement",
    "You’re the pulse that beats louder around you",
    "You’re the anchor of my wildest thoughts",
    "You’re the spark that fuels my poetic soul",
    "You’re the muse that turns my nights into verses",
    "You’re the rhythm that keeps me afloat",
    "You’re the glow that brightens my mundane moments",
    "You’re the melody that echoes in my heart",
    "You’re the calmness that settles my storms",
    "You’re the breeze that gives me breath",
    "You’re the pulse that makes every heartbeat a poem",
    "You’re the anchor that steadies my world",
    "You’re the spark that reignites my passions",
    "You’re the muse that turns my pain into poetry",
    "You’re the rhythm of my happiest memories",
    "You’re the glow that turns night into day",
    "You’re the melody that makes my silence sing",
    "You’re the calm sea I want to float forever on",
    "You’re the breeze that whispers my name sweetly",
    "You’re the pulse that creates music in my veins",
    "You’re the lighthouse in my journey of self-discovery",
    "You’re the spark that lights my purpose",
    "You’re the muse that writes my future",
    "You’re the rhythm that beats through my dreams",
    "You’re the glow that brightens my dark alleys",
    "You’re the melody that my heart can’t forget",
    "You’re the calm that soothes my restless nights",
    "You’re the breeze that sweeps me off my feet",
    "You’re the pulse that makes my love louder",
    "You’re the anchor that holds my fears down",
    "You’re the spark that turns my imaginations into reality",
    "You’re the muse that brings my visions to life",
    "You’re the rhythm that makes my world spin perfectly",
    "You’re the glow that outshines my worries",
    "You’re the melody that plays when I think of you",
    "You’re the calm that balances my energy",
    "You’re the breeze that lifts my tired spirit",
    "You’re the pulse that makes my heart smile",
    "You’re the lighthouse that guides my ambitions",
    "You’re the spark that sets my creativity ablaze",
    "You’re the muse that feeds my passion",
    "You’re the rhythm that writes through my life",
    "You’re the glow that makes my day shine",
    "You’re the melody that makes my thoughts sing",
    "You’re the calm that embraces my chaos",
    "You’re the breeze that clears my doubts",
    "You’re the pulse that keeps my heart alive",
    "You’re the anchor in my emotional tides",
    "You’re the spark that ignites my desires",
    "You’re the muse that crafts my dreams",
    "You’re the rhythm to my soul’s music",
    "You’re the glow that bathes my heart in light",
    "You’re the melody that lingers in my mind",
    "You’re the calm sea I find in your eyes",
    "You’re the breeze that touches my soul gently",
    "You’re the pulse that gives life to my fantasies",
    "You’re the lighthouse in my journey to greatness",
    "You’re the spark that brightens my every idea",
    "You’re the muse that writes my love songs",
    "You’re the rhythm that flows through my heartbeat",
    "You’re the glow that radiates through my smile",
    "You’re the melody that completes my silence",
    "You’re the calm after my mind’s hurricanes",
    "You’re the breeze that refreshes my thoughts",
    "You’re the pulse that syncs with my energy",
    "You’re the anchor of my peaceful moments",
    "You’re the spark that sets my spirit free",
    "You’re the muse that creates magic in my words",
    "You’re the rhythm that makes my heart race with joy",
    "You’re the glow that lights my path of dreams",
    "You’re the melody that soothes my inner chaos",
    "You’re the calm that shelters my restless mind",
    "You’re the breeze that carries my hopes higher",
    "You’re the pulse that beats in tune with yours",
    "You’re the lighthouse that keeps me from losing my way",
    "You’re the spark that ignites my hidden talents",
    "You’re the muse that shapes my brightest ideas",
    "You’re the rhythm that guides my every write",
    "You’re the glow that outshines every doubt",
    "You’re the melody that fills my quiet moments",
    "You’re the calm that I wrap around my worries",
    "You’re the breeze that lifts my ambitions",
    "You’re the pulse that makes me alive around you",
    "You’re the anchor of my wildest dreams",
    "You’re the spark that burns in my heart",
    "You’re the muse that whispers beauty into my thoughts",
    "You’re the rhythm that vibes with my happiness",
    "You’re the glow that paints my ordinary days golden",
    "You’re the melody that rewinds my favorite memories",
    "You’re the calm that hushes my storms",
    "You’re the breeze that refreshes my tiredness",
    "You’re the pulse that energizes my spirit",
    "You’re the lighthouse that guides me through uncertainties",
    "You’re the spark that lights up my darkest moments",
    "You’re the muse that turns my blank pages into masterpieces",
    "You’re the rhythm that composes my life’s symphony",
    "You’re the glow that reflects my inner beauty",
    "You’re the melody that my heart beats in sync with",
    "You’re the calm sea I drift in peacefully",
    "You’re the breeze that makes my worries fade",
    "You’re the pulse that makes every beat a story",
    "You’re the anchor that holds me steady in life",
    "You’re the spark that sets my journey in motion",
    "You’re the muse that writes my unwritten chapters",
    "You’re the rhythm that makes my life dance",
    "You’re the glow that fills my world with light",
    "You’re the melody that my heart sings endlessly",
    "You’re the calm that embraces my dreams gently",
    "You’re the breeze that carries my soul freely",
    "You’re the pulse that adds life to my existence",

    "You’re the reason my playlist turned into a love song collection,",
    "Are you Wi-Fi? Because I feel connected to you,",
    "I don’t need a map, I’ve already found my destination in you,",
    "You must be a candle because you light up my darkest days,",
    "If beauty was time, you’d be eternity,",
    "You’re the glitch in my matrix,",
    "I think my heart found its favorite rhythm with you,",
    "Are you a magician? Because every time you smile, everything else disappears,",
    "You’re not just a vibe, you’re the entire mood,",
    "Your eyes are like galaxies—every glance feels like a new adventure,",
    "You must be the CEO of beauty because you own it,",
    "You’ve got more elegance in your step than a runway show,",
    "If I had a rose for every time I thought of you, I’d be walking in a garden forever,",
    "You don’t need filters, you ARE the filter,",
    "Are you the ocean? Because I’m lost in your waves,",
    "You must be a bookmark because you keep my place in life,",
    "You’re the plot twist my story needed,",
    "You’re not a snack, you’re the whole buffet,",
    "You’re the Wi-Fi to my hotspot,",
    "The stars are jealous because you outshine them,",
    "You’re not my type, you’re my standard,",
    "You must be a compass because you give me direction,",
    "You’re the sunrise I never want to miss,",
    "My heart speaks fluent you,",
    "You’re the upgrade my life’s been waiting for,",
    "You’re not a dream, you’re the reality I prayed for,",
    "You’re the reason my phone battery dies—I can’t stop staring at your pictures,",
    "If you were a song, I’d keep you on repeat,",
    "You’re the emoji my heart’s been searching for,",
    "You’re the glitch that makes my life perfect,",
    "You’re the answer to questions I never knew I had,",
    "You’re not a moment; you’re a whole era,",
    "You’re the painting I’d stare at in a gallery for hours,",
    "You’re not a vibe check, you’re the entire exam,",
    "You’re the sunrise that makes my nights worth waiting through,",
    "You’re the reason the moon feels lonely,",
    "You must be a locksmith because you’ve got the key to my heart,",
    "You’re the spark before the flame,",
    "You’re the breeze in my chaos,",
    "You’re the page-turner in my story,",
    "You’re the horizon I keep chasing,",
    "You’re the favorite notification I wish I’d get,",
    "You’re the meaning behind my favorite lyrics,",
    "You’re the sequel I never want to end,",
    "You’re the calm in my storm,",
    "You’re the best coincidence life ever gave me,",
    "You’re not a chapter, you’re the entire book,",
    "You’re the compass in my lost moments,",
    "You’re the peace after a long day,",
    "You’re the warmth in my winter,",
    "You’re the rarest star in my sky,",
    "You’re the rhythm to my heartbeat,",
    "You’re the muse behind my late-night thoughts,",
    "You’re the spark that lights my creativity,",
    "You’re the melody in my silence,",
    "You’re the harmony in my chaos,",
    "You’re the breeze that cools my worries,",
    "You’re the sunshine after my rain,",
    "You’re the anchor in my stormy seas,",
    "You’re the caffeine to my tired soul,",
    "You’re the calm in my noisy mind,",
    "You’re the glow in my darkness,",
    "You’re the echo of my unspoken words,",
    "You’re the dream that feels real,",
    "You’re the lighthouse guiding me home,",
    "You’re the poetry in my prose,",
    "You’re the magic in my ordinary,",
    "You’re the gem in my treasure hunt,",
    "You’re the muse of my masterpiece,",
    "You’re the spark in my dull days,",
    "You’re the soft landing after my fall,",
    "You’re the song my heart hums to,",
    "You’re the missing piece in my puzzle,",
    "You’re the heartbeat I sync with,",
    "You’re the rhythm in my walk,",
    "You’re the masterpiece I can’t stop admiring,",
    "You’re the sunrise that colors my dreams,",
    "You’re the painting I want to live in,",
    "You’re the inspiration behind my best lines,",
    "You’re the peace treaty to my inner wars,",
    "You’re the fire that doesn’t burn but warms,",
    "You’re the chapter my life needed,",
    "You’re the flavor to my bland days,",
    "You’re the gravity pulling me in,",
    "You’re the definition of timeless beauty,",
    "You’re the upgrade to my standard life,",
    "You’re the peace in my late-night thoughts,",
    "You’re the vibe I can’t replace,",
    "You’re the aura that fills the room,",
    "You’re the favorite verse in my song,",
    "You’re the breath of fresh air,",
    "You’re the glow that neon signs wish they had,",
    "You’re the muse that artists dream of,",
    "You’re the color to my grayscale,",
    "You’re the melody my heart beats to,",
    "You’re the pulse of my daydreams,",
    "You’re the spark before the flame ignites,",
    "You’re the gravity to my floating thoughts,",
    "You’re the calm after my storms,",
    "You’re the quiet I crave after noise,",
    "You’re the rarest gem in the world,",
    "You’re the pause that makes my heart skip,",
    "You’re the echo I want to keep hearing,",
    "You’re the muse that fuels my creativity,",
    "You’re the horizon my eyes search for,",
    "You’re the gravity holding me down when I’m lost,",
    "You’re the calm in my emotional hurricanes,",
    "You’re the silence that speaks volumes,",
    "You’re the masterpiece of my admiration,",
    "You’re the reflection of my unspoken feelings,",
    "You’re the heartbeat syncing with mine,",
    "You’re the warmth I seek in cold nights,",
    "You’re the spark igniting my imagination,",
    "You’re the dream I never want to wake up from,",
    "You’re the lighthouse guiding me in the dark,",
    "You’re the poem I can’t stop reciting,",
    "You’re the muse of my soul,",
    "You’re the serenity in my chaos,",
    "You’re the painting my mind paints at night,",
    "You’re the note that completes my melody,",
    "You’re the rhythm to my heartbeat,",
    "You’re the glow in my darkest hours,",
    "You’re the fire that keeps me warm,",
    "You’re the wind that carries my worries away,",
    "You’re the muse inspiring my best art,",
    "You’re the calm sea after my storm,",
    "You’re the whisper in my silence,",
    "You’re the masterpiece in my gallery,",
    "You’re the spark that brightens my thoughts,",
    "You’re the anchor holding me steady,",
    "You’re the lyric I keep singing,",
    "You’re the muse that makes words flow,",
    "You’re the shimmer in my twilight,",
    "You’re the breeze on my warm days,",
    "You’re the story I want to read forever,",
    "You’re the reason I believe in magic,",
    "You’re the verse my heart recites,",
    "You’re the calm after my breakdown,",
    "You’re the spark igniting my heart,",
    "You’re the muse behind my daydreams,",
    "You’re the compass to my lost thoughts,",
    "You’re the harmony in my melody,",
    "You’re the breeze that soothes my soul,",
    "You’re the light guiding my way,",
    "You’re the favorite chapter in my life,",
    "You’re the painting in my mind’s gallery,",
    "You’re the whisper calming my fears,",
    "You’re the anchor grounding my chaos,",
    "You’re the spark lighting up my mind,",
    "You’re the song my heart sings,",
    "You’re the glow in my night sky,",
    "You’re the muse that sparks my passion,",
    "You’re the rhythm my heart dances to,",
    "You’re the breeze that cools my worries,",
    "You’re the lighthouse in my stormy nights,",
    "You’re the melody to my lyrics,",
    "You’re the peace after my emotional wars,",
    "You’re the spark igniting my creativity,",
    "You’re the calm sea in my hurricane,",
    "You’re the reason stars exist,",
    "You’re the pulse syncing with mine,",
    "You’re the dream my heart wants to live in,",
    "You’re the spark that fires up my inspiration,",
    "You’re the echo that stays in my heart,",
    "You’re the muse behind my silent songs,",
    "You’re the calm after my emotional tsunamis,",
    "You’re the poetry in my heartbeat,",
    "You’re the whisper I always listen to,",
    "You’re the glow in my silent nights,",
    "You’re the spark that makes my heart race,",
    "You’re the muse of my most beautiful chaos,",
    "You’re the rhythm that completes my melody,",
    "You’re the heartbeat of my daydreams,",
    "You’re the masterpiece of my imaginations,",
    "You’re the lighthouse of my dark nights,",
    "You’re the melody my soul hums,",
    "You’re the anchor to my floating thoughts,",
    "You’re the spark that ignites my words,",
    "You’re the glow that lights my imagination,",
    "You’re the harmony in my silent music,",
    "You’re the breeze in my suffocating days,",
    "You’re the calmness in my storms,",
    "You’re the rhythm my heart can’t resist,",
    "You’re the glow of my twilight,",
    "You’re the muse of my unwritten poems,",
    "You’re the calm after my thunder,",
    "You’re the spark before my explosion,",
    "You’re the melody of my heartbeat,",
    "You’re the echo in my empty rooms,",
    "You’re the lighthouse of my lost voyages,",
    "You’re the whisper in my loud world,",
    "You’re the masterpiece in my gallery of thoughts,",
    "You’re the rhythm of my chaotic heartbeat,",
    "You’re the glow in my dusky evenings,",
    "You’re the spark that ignites my silent nights,",
    "You’re the muse behind my favorite daydreams,",
    "You’re the harmony in my discord,",
    "You’re the calm after my roaring waves,",
    "You’re the spark that fuels my silent fire,",
    "You’re the lighthouse of my emotional storms,",
    "You’re the melody I always wanted to write,",
    "You’re the rhythm my soul dances to,",
    "You’re the breeze that calms my burning thoughts,",
    "You’re the glow in my darkest hours,",
    "You’re the whisper that silences my chaos,",
    "You’re the spark before my creative storm,",
    "You’re the calm sea after my emotional tides,",
    "You’re the muse of my artistic soul,",
    "You’re the rhythm to my silent music,",
    "You’re the glow of my fading light,",
    "You’re the melody that soothes my broken heart,",
    "You’re the lighthouse of my lost hopes,",
    "You’re the breeze that cools my restless nights,",
    "You’re the spark that lights my imaginations,",
    "You’re the calm after my emotional floods,",
    "You’re the muse behind my poetic nights,",
    "You’re the rhythm of my untold stories,",
    "You’re the glow in my shadowed dreams,",
    "You’re the melody to my heartbeat’s lyrics,",
    "You’re the lighthouse to my wandering soul,",
    "You’re the spark that reignites my passion,",
    "You’re the calm after my inner wars,",
    "You’re the muse that writes my silent songs,",
    "You’re the glow of my dreamy nights,",
    "You’re the rhythm my heart chooses to beat,",
    "You’re the lighthouse of my emotional wrecks,",
    "You’re the melody in my unspoken feelings,",
    "You’re the spark that fuels my artistic storm,",
    "You’re the calm sea in my turbulent emotions,",
    "You’re the muse of my colorful imaginations,",
    "You’re the rhythm to my soulful dance,",
    "You’re the glow that paints my dusky evenings,",
    "You’re the lighthouse guiding my creative journey,",
    "You’re the melody that completes my silent lyrics,",
    "You’re the spark igniting my poetic waves,",
    "You’re the calm breeze in my suffocating moments,",
    "You’re the muse of my imaginative realms,",
    "You’re the rhythm in my artistic heartbeat,",
    "You’re the glow that defines my golden hour,",
    "You’re the lighthouse navigating my emotional tides,",
    "You’re the melody that sings my heart’s desires,",
    "You’re the spark that brightens my dim thoughts,",
    "You’re the calm after my emotional whirlwinds,",
    "You’re the muse inspiring my silent odes,",
    "You’re the rhythm syncing with my dreams,",
    "You’re the glow that colors my faded sketches,",
    "You’re the lighthouse in my creative fog,",
    "You’re the melody in my wordless songs,",
    "You’re the spark igniting my vivid imaginations,",
    "You’re the calm sea in my emotional hurricanes,",
    "You’re the muse behind my hidden stories,",
    "You’re the rhythm that my soul drums to,",
    "You’re the glow of my midnight musings,",
    "You’re the lighthouse guiding my artistic voyages,",
    "You’re the melody that my silence hums to,",
    "You’re the spark that fuels my passion projects,",
    "You’re the calm after my mental avalanches,",
    "You’re the muse crafting my hidden verses,",
    "You’re the rhythm of my poetic heartbeat,",
    "You’re the glow in my foggy dawns,",
    "You’re the lighthouse shining on my creative path,",
    "You’re the melody to my heart’s sonnet,",
    "You’re the spark lighting my mind’s fireworks,",
    "You’re the calm breeze in my inner tempests,"

]

const rizzText = document.querySelector(".rizzText");
const rizzButton = document.querySelector(".rizzButton");
let typeInterval = null;

function generateRizz () {
    //stops any ongoing typing before starting a new one
    if (typeInterval) {
        clearInterval(typeInterval);
        typeInterval = null;
    }
    
    rizzText.innerHTML = "";

    const randomIndex = Math.floor(Math.random() * rizzList.length);
    const write = rizzList[randomIndex];
    
    let i = 0;
    const speed = 100;

    typeInterval = setInterval(() => {
        rizzText.innerHTML += write.charAt(i);
        i++ ;

        if (i >= write.length) {
            clearInterval(typeInterval);
        }
    }, speed);
}

